# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [develop, master]
  pull_request:

jobs:

  Lint:
    runs-on: ubuntu-latest
    env:
      # not needed for linting
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: '1'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint

  Schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npx ajv validate -s app/schema.json -d "{docs/examples/viewconfs,test/{view-configs,view-configs-more}}/*.json"

  Test:
    needs: [Lint, Schema]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      # required to run headless puppeteer on ubuntu-latest
      - name: Setup xvf
        env:
          DISPLAY: '0'
        run: |
          sudo apt-get install -y xvfb
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - run: pnpm install
      - name: Pre-bundle deps with Vite
        # prevents timeouts when running tests on clean install
        run: pnpm run optimize
      - run: pnpm test -- --static-logging # don't show progress bar in CI
